### ISSUE TITLE
 Is there no decoding code for bbox when testing?

### ISSUE THREAD

**Issue by maolaoke** [Stick-To/FCOS-tensorflow#1]

**Comment by Stick-To** [comment]
the code in FCOS.py 215-241       
               p3_y1 = grid_y3 - p3reg[..., 2]
                p3_y2 = grid_y3 + p3reg[..., 3]
                p3_x1 = grid_x3 - p3reg[..., 0]
                p3_x2 = grid_x3 + p3reg[..., 1]
                p4_y1 = grid_y4 - p4reg[..., 2]
                p4_y2 = grid_y4 + p4reg[..., 3]
                p4_x1 = grid_x4 - p4reg[..., 0]
                p4_x2 = grid_x4 + p4reg[..., 1]
                p5_y1 = grid_y5 - p5reg[..., 2]
                p5_y2 = grid_y5 + p5reg[..., 3]
                p5_x1 = grid_x5 - p5reg[..., 0]
                p5_x2 = grid_x5 + p5reg[..., 1]
                p6_y1 = grid_y6 - p6reg[..., 2]
                p6_y2 = grid_y6 + p6reg[..., 3]
                p6_x1 = grid_x6 - p6reg[..., 0]
                p6_x2 = grid_x6 + p6reg[..., 1]
                p7_y1 = grid_y7 - p7reg[..., 2]
                p7_y2 = grid_y7 + p7reg[..., 3]
                p7_x1 = grid_x7 - p7reg[..., 0]
                p7_x2 = grid_x7 + p7reg[..., 1]

                p3bbox = tf.reshape(tf.concat([p3_y1, p3_x1, p3_y2, p3_x2], axis=-1), [-1, 4]) * s3
                p4bbox = tf.reshape(tf.concat([p4_y1, p4_x1, p4_y2, p4_x2], axis=-1), [-1, 4]) * s4
                p5bbox = tf.reshape(tf.concat([p5_y1, p5_x1, p5_y2, p5_x2], axis=-1), [-1, 4]) * s5
                p6bbox = tf.reshape(tf.concat([p6_y1, p6_x1, p6_y2, p6_x2], axis=-1), [-1, 4]) * s6
                p7bbox = tf.reshape(tf.concat([p7_y1, p7_x1, p7_y2, p7_x2], axis=-1), [-1, 4]) * s7
                pbbox = tf.concat([p3bbox, p4bbox, p5bbox, p6bbox, p7bbox], axis=0)

**Comment by maolaoke** [comment]
get it.thank you!




------------------ 原始邮件 ------------------
发件人: "Stick-To"<notifications@github.com>;
发送时间: 2019年6月15日(星期六) 下午5:51
收件人: "Stick-To/FCOS-tensorflow"<FCOS-tensorflow@noreply.github.com>;
抄送: "陈意"<1249459910@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Stick-To/FCOS-tensorflow]  Is there no decoding code for bboxwhen testing? (#1)




the code in FCOS.py 215-241
 p3_y1 = grid_y3 - p3reg[..., 2]
 p3_y2 = grid_y3 + p3reg[..., 3]
 p3_x1 = grid_x3 - p3reg[..., 0]
 p3_x2 = grid_x3 + p3reg[..., 1]
 p4_y1 = grid_y4 - p4reg[..., 2]
 p4_y2 = grid_y4 + p4reg[..., 3]
 p4_x1 = grid_x4 - p4reg[..., 0]
 p4_x2 = grid_x4 + p4reg[..., 1]
 p5_y1 = grid_y5 - p5reg[..., 2]
 p5_y2 = grid_y5 + p5reg[..., 3]
 p5_x1 = grid_x5 - p5reg[..., 0]
 p5_x2 = grid_x5 + p5reg[..., 1]
 p6_y1 = grid_y6 - p6reg[..., 2]
 p6_y2 = grid_y6 + p6reg[..., 3]
 p6_x1 = grid_x6 - p6reg[..., 0]
 p6_x2 = grid_x6 + p6reg[..., 1]
 p7_y1 = grid_y7 - p7reg[..., 2]
 p7_y2 = grid_y7 + p7reg[..., 3]
 p7_x1 = grid_x7 - p7reg[..., 0]
 p7_x2 = grid_x7 + p7reg[..., 1]
             p3bbox = tf.reshape(tf.concat([p3_y1, p3_x1, p3_y2, p3_x2], axis=-1), [-1, 4]) * s3             p4bbox = tf.reshape(tf.concat([p4_y1, p4_x1, p4_y2, p4_x2], axis=-1), [-1, 4]) * s4             p5bbox = tf.reshape(tf.concat([p5_y1, p5_x1, p5_y2, p5_x2], axis=-1), [-1, 4]) * s5             p6bbox = tf.reshape(tf.concat([p6_y1, p6_x1, p6_y2, p6_x2], axis=-1), [-1, 4]) * s6             p7bbox = tf.reshape(tf.concat([p7_y1, p7_x1, p7_y2, p7_x2], axis=-1), [-1, 4]) * s7             pbbox = tf.concat([p3bbox, p4bbox, p5bbox, p6bbox, p7bbox], axis=0)
