### ISSUE TITLE
Weight Load Issue

### ISSUE THREAD

**Issue by RocccYan** [Stick-To/FCOS-tensorflow#5]
When I ran the code, it raised an error at line '**fcos .load_weight('./fcos/test-95778')**. 
I wonder what file should I put under that path? is the 'weight' here means the pre-trained model? should I download a pre-trained model and if that what file type does it expect, like ckpt or pb?
Thanks!

**Comment by Stick-To** [comment]
it is the checkpoint, continuation on break point.
pretrained weight could be loaded by load_pretrained_weight

**Comment by iimmortall** [comment]
Hi, I use the load_pretrained_weight function with [resnet v2 model](http://download.tensorflow.org/models/resnet_v2_50_2017_04_14.tar.gz), but failed, 
Can you provide the tutorial that load and download a pre-trained model.

**Comment by Stick-To** [comment]
@iimmortall  Sorry, I have not keeped the pretrianed weight

**Comment by iimmortall** [comment]
@Stick-To Did you train the pre-trained model based on ImageNet, or train the fcos without pre-trained model? Thanks.

**Comment by Stick-To** [comment]
@iimmortall  I have pretrained with some epochs, and you also could train it from scratch
